repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.12.0
    hooks:
      - id: typos
        args: []
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: cargo fmt -- --config "unstable_features=true,imports_granularity=Crate,group_imports=StdExternalCrate,format_code_in_doc_comments=true"
        language: rust
        pass_filenames: false
        types_or: [rust, toml]
      - id: clippy
        name: clippy
        entry: cargo clippy --no-default-features -- -D warnings
        language: rust
        pass_filenames: false
        types_or: [rust, toml]
      - id: clippy
        name: clippy
        entry: cargo clippy --all-features --tests -- -D warnings
        language: rust
        pass_filenames: false
        types_or: [rust, toml]
