[package]
name = "swap-buffer-queue"
version = "0.1.0"
edition = "2021"

[features]
buffer = []
async = ["std", "dep:futures", "dep:tokio"]
std = []
sync = ["std"]
write = []
write-vectored = ["std"]

[dependencies]
futures = { version = "0.3", optional = true }
tokio = { version = "1", features = ["sync"], optional = true }

[dev-dependencies]
tokio-test = "0.4"

[target.'cfg(loom)'.dev-dependencies]
loom = "0.5"


# See tokio Cargo.toml
[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
]
